name: Test compatibility with puppeteer

on:
  pull_request: ~
  workflow_dispatch: ~

jobs:
  test-compatibility:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout website-scraper-puppeteer
        uses: actions/checkout@v4
        with:
          repository: website-scraper/website-scraper-puppeteer
          ref: add-compatibility-bridge

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Install version bridge package from the branch
        run: npm install website-scraper/puppeteer-version-wrapper#${{ github.head_ref }} --save

      - name: Disable AppArmor
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns

      - name: Run tests
        run: npm test
