name: Test compatibility with puppeteer

on: pull_request

jobs:
  test-compatibility:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository (PR)
        uses: actions/checkout@v4

      - name: Clone website-scraper-puppeteer
        run: git clone --single-branch --branch add-compatibility-bridge https://github.com/website-scraper/website-scraper-puppeteer.git

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        working-directory: ./website-scraper-puppeteer
        run: npm install

      - name: Install compatibility package from the branch
        working-directory: ./website-scraper-puppeteer
        run: npm install website-scraper/website-scraper-puppeteer-compatibility-bridge#${{ github.head_ref }} --save

      - name: Disable AppArmor
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns

      - name: Run tests
        working-directory: ./website-scraper-puppeteer
        run: npm test
